language: generic

script:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker-compose build
  - docker images
  - docker-compose up

after_success:
  - docker-compose push

# safelist
branches:
  only:
  - master

# no need to pollute inboxes
notifications:
  email: false
