version: '2'

services:
  uniaudio:
    image: mkaichen/uni_audio:latest
    environment:
      - DB_HOST=centralmongodb
      - AUDIOSEARCH_APP_ID=$AUDIOSEARCH_APP_ID
      - AUDIOSEARCH_SECRET=$AUDIOSEARCH_SECRET
    ports:
      - '8080:8080'
    depends_on: 
      - centralmongodb

  uniaudio-test:
    image: mkaichen/uni_audio:latest
    build: .
    command: [ "npm", "test" ]

  centralmongodb:
    image: mongo:latest
    volumes: 
      - /data/database
    restart: always
